import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ColumnDefinition, ColumnKind, SchemaDefinition, TableDefinition } from '../orm';

export interface MigrationJournalEntry {
  idx: number;
  when: number;
  tag: string;
  filename: string;
  snapshot: string;
}

export interface MigrationJournal {
  version: '1';
  dialect: 'postgresql';
  entries: MigrationJournalEntry[];
}

export interface MigrationFile {
  id: string;
  idx: number;
  tag: string;
  filename: string;
  path: string;
  snapshotPath: string;
  sql: string;
  hash: string;
  createdAt: number;
}

export interface GeneratedMigrationResult {
  created: boolean;
  journalPath: string;
  migration?: MigrationFile;
}

export type MigrationSqlExecutor = (sql: string, parameters: unknown[]) => Promise<unknown>;

const MIGRATIONS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS "public"."__kuradb_migrations" (
  "id" VARCHAR(255) PRIMARY KEY,
  "tag" VARCHAR(255) NOT NULL,
  "hash" VARCHAR(64) NOT NULL,
  "applied_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
`.trim();

const EMPTY_JOURNAL: MigrationJournal = {
  version: '1',
  dialect: 'postgresql',
  entries: [],
};

const defaultMigrationSqlExecutor: MigrationSqlExecutor = (sql, parameters) => {
  const { executeQuery } =
    require('../queryBuilder/execute') as typeof import('../queryBuilder/execute');
  return executeQuery('query', sql, parameters);
};

export function generateCreateTableSQL(table: TableDefinition<any>): string {
  const columns: string[] = [];

  for (const [, col] of Object.entries(table.columns) as [string, ColumnDefinition][]) {
    let colDef = `"${col.name}" ${mapColumnTypeToSQL(col.kind)}`;

    if (col.primaryKey) colDef += ' PRIMARY KEY';
    if (!col.nullable && !col.primaryKey) colDef += ' NOT NULL';
    if (col.defaultExpression) colDef += ` DEFAULT ${col.defaultExpression}`;

    columns.push(colDef);
  }

  return `CREATE TABLE IF NOT EXISTS "${table.schema}"."${table.name}" (\n  ${columns.join(',\n  ')}\n);`;
}

export function generateDropTableSQL(table: TableDefinition<any>): string {
  return `DROP TABLE IF EXISTS "${table.schema}"."${table.name}";`;
}

export async function ensureMigrationTable(
  sqlExecutor: MigrationSqlExecutor = defaultMigrationSqlExecutor
): Promise<void> {
  await sqlExecutor(MIGRATIONS_TABLE_SQL, []);
}

export async function getAppliedMigrations(
  sqlExecutor: MigrationSqlExecutor = defaultMigrationSqlExecutor
): Promise<Map<string, { hash: string }>> {
  await ensureMigrationTable(sqlExecutor);

  const rows = (await sqlExecutor(
    'SELECT "id", "hash" FROM "public"."__kuradb_migrations" ORDER BY "applied_at" ASC',
    []
  )) as Array<{ id: string; hash: string }>;

  return new Map(rows.map((row) => [row.id, { hash: row.hash }]));
}

export async function recordAppliedMigration(
  migration: MigrationFile,
  sqlExecutor: MigrationSqlExecutor = defaultMigrationSqlExecutor
): Promise<void> {
  await ensureMigrationTable(sqlExecutor);
  await sqlExecutor(
    `
      INSERT INTO "public"."__kuradb_migrations" ("id", "tag", "hash")
      VALUES ($1, $2, $3)
    `,
    [migration.id, migration.tag, migration.hash]
  );
}

export function createMigrationFromSchema(
  basePath: string,
  schema: SchemaDefinition,
  customName?: string
): GeneratedMigrationResult {
  const journal = readMigrationJournal(basePath);
  const migrationsDir = getMigrationsDirectory(basePath);
  const metaDir = getMigrationMetaDirectory(basePath);
  const journalPath = getMigrationJournalPath(basePath);
  const snapshot = serializeSchemaSnapshot(schema);
  const latestEntry = journal.entries.at(-1);

  if (latestEntry) {
    const latestSnapshotPath = join(metaDir, latestEntry.snapshot);
    if (existsSync(latestSnapshotPath) && readFileSync(latestSnapshotPath, 'utf8') === snapshot) {
      return { created: false, journalPath };
    }
  } else if (Object.keys(schema.tables).length === 0) {
    return { created: false, journalPath };
  }

  const idx = journal.entries.length;
  const prefix = String(idx).padStart(4, '0');
  const tag = slugify(customName || getDefaultMigrationTag(journal, schema));
  const filename = `${prefix}_${tag}.sql`;
  const snapshotFilename = `${prefix}_snapshot.json`;
  const createdAt = Date.now();

  const sql = [
    '-- Auto-generated by kuradb',
    `-- Tag: ${tag}`,
    `-- Generated at: ${new Date(createdAt).toISOString()}`,
    '',
    buildSchemaMigrationSQL(schema),
    '',
  ].join('\n');

  const migrationPath = join(migrationsDir, filename);
  const snapshotPath = join(metaDir, snapshotFilename);

  writeFileSync(migrationPath, sql);
  writeFileSync(snapshotPath, snapshot);

  const entry: MigrationJournalEntry = {
    idx,
    when: createdAt,
    tag,
    filename,
    snapshot: snapshotFilename,
  };

  writeMigrationJournal(basePath, {
    ...journal,
    entries: [...journal.entries, entry],
  });

  return {
    created: true,
    journalPath,
    migration: loadMigrationFromEntry(basePath, entry),
  };
}

export function getAllMigrations(basePath: string): MigrationFile[] {
  const journal = readMigrationJournal(basePath);
  return journal.entries.map((entry) => loadMigrationFromEntry(basePath, entry));
}

export async function getPendingMigrations(
  basePath: string,
  sqlExecutor: MigrationSqlExecutor = defaultMigrationSqlExecutor
): Promise<MigrationFile[]> {
  const migrations = getAllMigrations(basePath);
  const applied = await getAppliedMigrations(sqlExecutor);

  for (const migration of migrations) {
    const appliedMigration = applied.get(migration.id);
    if (appliedMigration && appliedMigration.hash !== migration.hash) {
      throw new Error(
        `Applied migration "${migration.filename}" was modified on disk. Restore it or create a new migration.`
      );
    }
  }

  return migrations.filter((migration) => !applied.has(migration.id));
}

function mapColumnTypeToSQL(kind: ColumnKind | string): string {
  const typeMap: Record<string, string> = {
    uuid: 'UUID',
    ulid: 'CHAR(26)',
    string: 'VARCHAR(255)',
    number: 'INTEGER',
    integer: 'INTEGER',
    boolean: 'BOOLEAN',
    date: 'TIMESTAMP',
    timestamptz: 'TIMESTAMPTZ',
    json: 'JSONB',
    jsonb: 'JSONB',
    bigint: 'BIGINT',
    custom: 'TEXT',
  };

  return typeMap[kind] || 'TEXT';
}

function buildSchemaMigrationSQL(schema: SchemaDefinition): string {
  return Object.entries(schema.tables)
    .sort(([leftName], [rightName]) => leftName.localeCompare(rightName))
    .map(([, table]) => generateCreateTableSQL(table))
    .join('\n\n');
}

function getMigrationsDirectory(basePath: string): string {
  const dir = join(basePath, 'migrations');
  ensureDirectory(dir);
  return dir;
}

function getMigrationMetaDirectory(basePath: string): string {
  const dir = join(getMigrationsDirectory(basePath), 'meta');
  ensureDirectory(dir);
  return dir;
}

function getMigrationJournalPath(basePath: string): string {
  return join(getMigrationMetaDirectory(basePath), '_journal.json');
}

function ensureDirectory(path: string) {
  if (!existsSync(path)) {
    mkdirSync(path, { recursive: true });
  }
}

function readMigrationJournal(basePath: string): MigrationJournal {
  const journalPath = getMigrationJournalPath(basePath);

  if (!existsSync(journalPath)) {
    writeMigrationJournal(basePath, EMPTY_JOURNAL);
    return EMPTY_JOURNAL;
  }

  const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as Partial<MigrationJournal>;
  return {
    version: journal.version === '1' ? journal.version : '1',
    dialect: 'postgresql',
    entries: Array.isArray(journal.entries) ? journal.entries : [],
  };
}

function writeMigrationJournal(basePath: string, journal: MigrationJournal) {
  writeFileSync(getMigrationJournalPath(basePath), `${JSON.stringify(journal, null, 2)}\n`);
}

function loadMigrationFromEntry(basePath: string, entry: MigrationJournalEntry): MigrationFile {
  const migrationPath = join(getMigrationsDirectory(basePath), entry.filename);
  if (!existsSync(migrationPath)) {
    throw new Error(`Migration file is missing: ${migrationPath}`);
  }

  const sql = readFileSync(migrationPath, 'utf8');

  return {
    id: entry.filename.replace(/\.sql$/i, ''),
    idx: entry.idx,
    tag: entry.tag,
    filename: entry.filename,
    path: migrationPath,
    snapshotPath: join(getMigrationMetaDirectory(basePath), entry.snapshot),
    sql,
    hash: createHash('sha256').update(sql).digest('hex'),
    createdAt: entry.when,
  };
}

function getDefaultMigrationTag(journal: MigrationJournal, schema: SchemaDefinition): string {
  if (journal.entries.length === 0) {
    const tableNames = Object.values(schema.tables)
      .map((table) => table.name)
      .sort();

    if (tableNames.length === 0) return 'initial_schema';
    if (tableNames.length <= 3) return `init_${tableNames.join('_')}`;
    return 'initial_schema';
  }

  return 'schema_update';
}

function slugify(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  return normalized || 'schema_update';
}

function serializeSchemaSnapshot(schema: SchemaDefinition): string {
  const snapshot = {
    version: 1,
    schema: {
      name: schema.name,
      tables: Object.fromEntries(
        Object.entries(schema.tables)
          .sort(([leftName], [rightName]) => leftName.localeCompare(rightName))
          .map(([tableKey, table]) => [
            tableKey,
            {
              schema: table.schema,
              name: table.name,
              primaryKey: [...table.primaryKey],
              columns: Object.fromEntries(
                (Object.entries(table.columns) as [string, ColumnDefinition][])
                  .sort(([leftName], [rightName]) => leftName.localeCompare(rightName))
                  .map(([columnKey, column]) => [
                    columnKey,
                    {
                      name: column.name,
                      kind: column.kind,
                      nullable: !!column.nullable,
                      primaryKey: !!column.primaryKey,
                      defaultExpression: column.defaultExpression ?? null,
                    },
                  ])
              ),
            },
          ])
      ),
    },
  };

  return `${JSON.stringify(snapshot, null, 2)}\n`;
}
