import { writeFileSync } from 'node:fs';
import type { ColumnDefinition, ColumnKind, SchemaDefinition } from '../orm';

export function generateLuaTypes(schema: SchemaDefinition, outputPath: string): void {
  const lines: string[] = [];

  lines.push('-- Auto-generated by kuradb');
  lines.push('-- Update by running: kuradb generate --types-only');
  lines.push('');

  for (const [tableName, table] of Object.entries(schema.tables)) {
    const rowClassName = `${pascalCase(tableName)}Row`;
    const insertClassName = `${pascalCase(tableName)}Insert`;
    const updateClassName = `${pascalCase(tableName)}Update`;
    const tableClassName = `${pascalCase(tableName)}Table`;

    emitRowClass(lines, rowClassName, table.columns);
    emitInsertClass(lines, insertClassName, table.columns);
    emitUpdateClass(lines, updateClassName, table.columns);
    lines.push(
      `---@class ${tableClassName} : KuraDBTable<${rowClassName}, ${insertClassName}, ${updateClassName}>`
    );
    lines.push('');
  }

  lines.push('---@class kuradb_schema');
  for (const [tableName] of Object.entries(schema.tables)) {
    const tableClassName = `${pascalCase(tableName)}Table`;
    lines.push(`---@field ${tableName} ${tableClassName}`);
  }
  lines.push('');

  lines.push('---@type kuradb_schema');
  lines.push('local schema = {}');
  lines.push('');

  for (const [tableName, table] of Object.entries(schema.tables)) {
    const tableClassName = `${pascalCase(tableName)}Table`;
    const columnMapEntries = Object.entries(table.columns as Record<string, ColumnDefinition>)
      .map(([propertyName, col]) => `    ${propertyName} = '${col.name}',`)
      .join('\n');
    const primaryKeyEntries = table.primaryKey.map((colName) => `'${colName}'`).join(', ');

    lines.push(`---@type ${tableClassName}`);
    lines.push(`schema.${tableName} = {`);
    lines.push(`  schema = '${table.schema}',`);
    lines.push(`  name = '${table.name}',`);
    lines.push('  columns = {');
    lines.push(columnMapEntries);
    lines.push('  },');
    lines.push(`  primaryKey = { ${primaryKeyEntries} },`);
    lines.push('}');
    lines.push('');
  }

  lines.push('_ENV.kura = _ENV.kura or {}');
  lines.push('_ENV.kura.db = _ENV.kura.db or {}');
  lines.push('kura.db.tables = schema');
  lines.push('');
  lines.push('return schema');

  writeFileSync(outputPath, lines.join('\n'));
}

function pascalCase(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

function mapColumnTypeToLua(kind: ColumnKind | string): string {
  const typeMap: Record<string, string> = {
    uuid: 'string',
    string: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'number',
    json: 'table',
    bigint: 'number',
    custom: 'any',
  };

  return typeMap[kind] || 'any';
}

function emitRowClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    const fieldType = mapColumnTypeToLua(column.kind);
    const nullableSuffix = column.nullable ? '?' : '';
    lines.push(`---@field ${propertyName} ${fieldType}${nullableSuffix}`);
  }
  lines.push('');
}

function emitInsertClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    const fieldType = mapColumnTypeToLua(column.kind);
    const optionalMarker = isOptionalInsertField(column) ? '?' : '';
    lines.push(`---@field ${propertyName}${optionalMarker} ${fieldType}`);
  }
  lines.push('');
}

function emitUpdateClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    const fieldType = mapColumnTypeToLua(column.kind);
    lines.push(`---@field ${propertyName}? ${fieldType}`);
  }
  lines.push('');
}

function isOptionalInsertField(column: ColumnDefinition): boolean {
  return Boolean(column.nullable || column.defaultExpression);
}
