import { writeFileSync } from 'node:fs';
import type { ColumnDefinition, ColumnKind, SchemaDefinition } from '../orm';

export function generateLuaTypes(schema: SchemaDefinition, outputPath: string): void {
  const lines: string[] = [];

  lines.push('-- Auto-generated by kuradb');
  lines.push('-- Update by running: kuradb generate --types-only');
  lines.push('');

  for (const [tableName, table] of Object.entries(schema.tables)) {
    const rowClassName = `${pascalCase(tableName)}Row`;
    const insertClassName = `${pascalCase(tableName)}Insert`;
    const updateClassName = `${pascalCase(tableName)}Update`;
    const columnsClassName = `${pascalCase(tableName)}Columns`;
    const tableClassName = `${pascalCase(tableName)}Table`;

    emitRowClass(lines, rowClassName, table.columns);
    emitInsertClass(lines, insertClassName, table.columns);
    emitUpdateClass(lines, updateClassName, table.columns);
    emitColumnsClass(lines, columnsClassName, table.columns);
    lines.push(
      `---@class ${tableClassName} : KuraDBTable<${rowClassName}, ${insertClassName}, ${updateClassName}>`
    );
    lines.push(`---@field columns table<string, string>`);
    lines.push(`---@field columnOrder string[]`);
    lines.push(`---@field columnRefs ${columnsClassName}`);
    for (const [propertyName, column] of Object.entries(
      table.columns as Record<string, ColumnDefinition>
    )) {
      if (isReservedTableField(propertyName)) continue;
      lines.push(`---@field ${propertyName} ${columnRefType(column)}`);
    }
    lines.push('');
  }

  lines.push('---@class kuradb_schema');
  for (const [tableName] of Object.entries(schema.tables)) {
    const tableClassName = `${pascalCase(tableName)}Table`;
    lines.push(`---@field ${tableName} ${tableClassName}`);
  }
  lines.push('');

  lines.push('---@type kuradb_schema');
  lines.push('local schema = {}');
  lines.push('');

  for (const [tableName, table] of Object.entries(schema.tables)) {
    const tableClassName = `${pascalCase(tableName)}Table`;
    const columnMapEntries = Object.entries(table.columns as Record<string, ColumnDefinition>)
      .map(([propertyName, col]) => `    ${propertyName} = '${col.name}',`)
      .join('\n');
    const columnOrderEntries = Object.keys(table.columns)
      .map((propertyName) => `    '${propertyName}',`)
      .join('\n');
    const columnRefEntries = Object.entries(table.columns as Record<string, ColumnDefinition>)
      .map(([propertyName, col]) =>
        [
          `    ${propertyName} = {`,
          `      schema = '${table.schema}',`,
          `      table = '${table.name}',`,
          `      luaName = '${propertyName}',`,
          `      sqlName = '${col.name}',`,
          `      kind = '${col.kind}',`,
          `      nullable = ${luaBoolean(Boolean(col.nullable))},`,
          '    },',
        ].join('\n')
      )
      .join('\n');
    const primaryKeyEntries = table.primaryKey.map((colName) => `'${colName}'`).join(', ');

    lines.push(`---@type ${tableClassName}`);
    lines.push(`schema.${tableName} = {`);
    lines.push(`  schema = '${table.schema}',`);
    lines.push(`  name = '${table.name}',`);
    lines.push('  columns = {');
    lines.push(columnMapEntries);
    lines.push('  },');
    lines.push('  columnOrder = {');
    lines.push(columnOrderEntries);
    lines.push('  },');
    lines.push('  columnRefs = {');
    lines.push(columnRefEntries);
    lines.push('  },');
    lines.push(`  primaryKey = { ${primaryKeyEntries} },`);
    lines.push('}');
    lines.push('');
    for (const [propertyName] of Object.entries(
      table.columns as Record<string, ColumnDefinition>
    )) {
      if (isReservedTableField(propertyName)) continue;
      lines.push(
        `schema.${tableName}.${propertyName} = schema.${tableName}.columnRefs.${propertyName}`
      );
    }
    lines.push('');
  }

  lines.push('_ENV.kura = _ENV.kura or {}');
  lines.push('_ENV.kura.db = _ENV.kura.db or {}');
  lines.push('kura.db.tables = schema');
  lines.push('');
  lines.push('return schema');

  writeFileSync(outputPath, lines.join('\n'));
}

function pascalCase(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

function mapColumnTypeToLua(kind: ColumnKind | string): string {
  const typeMap: Record<string, string> = {
    uuid: 'string',
    ulid: 'string',
    string: 'string',
    number: 'number',
    integer: 'number',
    boolean: 'boolean',
    date: 'number',
    timestamptz: 'number',
    json: 'table',
    jsonb: 'table',
    bigint: 'number',
    custom: 'any',
  };

  return typeMap[kind] || 'any';
}

function emitRowClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    const fieldType = mapColumnTypeToLua(column.kind);
    const nullableSuffix = column.nullable ? '?' : '';
    lines.push(`---@field ${propertyName} ${fieldType}${nullableSuffix}`);
  }
  lines.push('');
}

function emitInsertClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    const fieldType = mapColumnTypeToLua(column.kind);
    const optionalMarker = isOptionalInsertField(column) ? '?' : '';
    lines.push(`---@field ${propertyName}${optionalMarker} ${fieldType}`);
  }
  lines.push('');
}

function emitUpdateClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    const fieldType = mapColumnTypeToLua(column.kind);
    lines.push(`---@field ${propertyName}? ${fieldType}`);
  }
  lines.push('');
}

function emitColumnsClass(
  lines: string[],
  className: string,
  columns: Record<string, ColumnDefinition>
): void {
  lines.push(`---@class ${className}`);
  for (const [propertyName, column] of Object.entries(columns)) {
    lines.push(`---@field ${propertyName} ${columnRefType(column)}`);
  }
  lines.push('');
}

function isOptionalInsertField(column: ColumnDefinition): boolean {
  return Boolean(column.nullable || column.defaultExpression);
}

function columnRefType(column: ColumnDefinition): string {
  return `KuraDBColumnRef<${mapColumnTypeToLua(column.kind)}>`;
}

function luaBoolean(value: boolean): string {
  return value ? 'true' : 'false';
}

function isReservedTableField(fieldName: string): boolean {
  return RESERVED_TABLE_FIELDS.has(fieldName);
}

const RESERVED_TABLE_FIELDS = new Set([
  'schema',
  'name',
  'columns',
  'columnOrder',
  'columnRefs',
  'primaryKey',
]);
