import { writeFileSync } from 'node:fs';
import type { ColumnDefinition, ColumnKind, SchemaDefinition } from '../orm';

export function generateLuaTypes(schema: SchemaDefinition, outputPath: string): void {
  const lines: string[] = [];

  lines.push('-- Auto-generated by kuradb');
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push('-- Update by running: kuradb generate');
  lines.push('');

  // EmmyLua row type annotations
  for (const [tableName, table] of Object.entries(schema.tables)) {
    const className = `${pascalCase(tableName)}Row`;

    lines.push(`---@class ${className}`);
    for (const [colName, col] of Object.entries(table.columns) as [string, ColumnDefinition][]) {
      const luaType = mapColumnTypeToLua(col.kind);
      const nullable = col.nullable ? '?' : '';
      lines.push(`---@field ${colName} ${luaType}${nullable}`);
    }
    lines.push('');
  }

  lines.push('---@class kuradb_schema');
  for (const tableName of Object.keys(schema.tables)) {
    const className = `${pascalCase(tableName)}Row`;
    lines.push(`---@field ${tableName} ${className}[]`);
  }
  lines.push('');

  // Export table definitions usable by the Lua query builder
  lines.push('local schema = {}');
  lines.push('');

  for (const [tableName, table] of Object.entries(schema.tables)) {
    const colNames = Object.entries(table.columns as Record<string, ColumnDefinition>)
      .map(([, col]) => `'${col.name}'`)
      .join(', ');

    lines.push(`schema.${tableName} = {`);
    lines.push(`  schema = '${table.schema}',`);
    lines.push(`  name = '${table.name}',`);
    lines.push(`  columns = { ${colNames} },`);
    lines.push('}');
    lines.push('');
  }

  lines.push('_ENV.kura = _ENV.kura or {}');
  lines.push('_ENV.kura.db = _ENV.kura.db or {}');
  lines.push('kura.db.tables = schema');
  lines.push('');
  lines.push('return schema');

  writeFileSync(outputPath, lines.join('\n'));
}

function pascalCase(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

function mapColumnTypeToLua(kind: ColumnKind | string): string {
  const typeMap: Record<string, string> = {
    uuid: 'string',
    string: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'number',
    json: 'table',
    bigint: 'number',
    custom: 'any',
  };

  return typeMap[kind] || 'any';
}
